[changelog]
# Path to the changelog file
path = "CHANGELOG.md"
# Template for the changelog
template = """
# Changelog

All notable changes to this project will be documented in this file.

{{#each releases}}
## [{{version}}] - {{date}}
{{#if title}}
### {{title}}
{{/if}}
{{#each commits}}
- {{#if scope}}**{{scope}}:** {{/if}}{{subject}}
{{/each}}

{{/each}}
"""

[commit_types]
# Conventional commit types
feat = { changelog = "Features", hidden = false }
fix = { changelog = "Bug Fixes", hidden = false }
docs = { changelog = "Documentation", hidden = false }
style = { changelog = "Style", hidden = false }
refactor = { changelog = "Refactoring", hidden = false }
perf = { changelog = "Performance", hidden = false }
test = { changelog = "Tests", hidden = false }
build = { changelog = "Build", hidden = false }
ci = { changelog = "CI", hidden = false }
chore = { changelog = "Chores", hidden = false }
revert = { changelog = "Reverts", hidden = false }

[commit_parsing]
# Conventional commit parsing rules
default_author = "OpenAPI K8s Operator Contributors"
conventional_commits = true
filter_merge_commits = true
filter_revert_commits = true

[hook]
# Pre-commit hook configuration
prepend_issue = false
