# Example service with API documentation annotations
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  annotations:
    api-doc.io/enabled: "true"
    api-doc.io/name: "User Service API"
    api-doc.io/description: "User management and authentication API"
    api-doc.io/path: "/swagger/openapi.yml"
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
    spec:
      containers:
        - name: user-service
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
