{{- if .Values.operator.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openapi-k8s-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openapi-k8s-operator.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "openapi-k8s-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace.name }}
    ports:
    - protocol: TCP
      port: 8080
  {{- if include "openapi-k8s-operator.clusterWideNetworkPolicy" . }}
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  {{- end }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace.name }}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  {{- if include "openapi-k8s-operator.clusterWideNetworkPolicy" . }}
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  {{- end }}
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
{{- end }}
