{{- if and .Values.openapiServer.enabled .Values.operator.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openapi-k8s-operator.serverName" . }}-networkpolicy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openapi-k8s-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: openapi-server
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "openapi-k8s-operator.name" . }}
      app.kubernetes.io/component: openapi-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - protocol: TCP
      port: 8080
  # Allow ingress from any namespace (OpenAPI server should be accessible cluster-wide)
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow communication with Kubernetes API server
  - to: []
    ports:
    - protocol: TCP
      port: 443  # HTTPS (Kubernetes API server)
    - protocol: TCP
      port: 6443 # Alternative Kubernetes API server port
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow communication with services in the same namespace
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080
  # Allow communication with services across all namespaces (for fetching OpenAPI specs)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 3000
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 10000
{{- end }}
