{{- if .Values.operator.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openapi-k8s-operator.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "openapi-k8s-operator.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.operator.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openapi-k8s-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.operator.serviceMonitor.interval | default "30s" }}
    scrapeTimeout: {{ .Values.operator.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
