name: Conventional Commits

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-commits:
    name: Validate Conventional Commits with Cocogitto
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Validate commit messages
      uses: cocogitto/cocogitto-action@v3
