name: Conventional Commits

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-commits:
    name: Validate Conventional Commits with Cocogitto
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install Cocogitto
      run: |
        # Install jq for JSON parsing
        sudo apt-get update && sudo apt-get install -y jq
        # Install Cocogitto binary using direct release URL
        COCOGITTO_VERSION=$(curl -s https://api.github.com/repos/cocogitto/cocogitto/releases/latest | jq -r '.tag_name')
        curl -sSL "https://github.com/cocogitto/cocogitto/releases/download/${COCOGITTO_VERSION}/cocogitto-${COCOGITTO_VERSION}-x86_64-unknown-linux-musl.tar.gz" | tar -xz
        sudo mv cocogitto /usr/local/bin/
        chmod +x /usr/local/bin/cocogitto
        cocogitto --version
        
    - name: Validate commit messages
      run: |
        cocogitto check
