name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_OPERATOR: ${{ github.repository }}-operator
  IMAGE_NAME_SERVER: ${{ github.repository }}-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract operator version
        id: operator-version
        run: |
          OPERATOR_VERSION=$(grep '^version = ' crates/openapi-k8s-operator/Cargo.toml | cut -d'"' -f2)
          echo "OPERATOR_VERSION=$OPERATOR_VERSION" >> $GITHUB_OUTPUT
          echo "Operator version: $OPERATOR_VERSION"

      - name: Extract server version
        id: server-version
        run: |
          SERVER_VERSION=$(grep '^version = ' crates/openapi-doc-server/Cargo.toml | cut -d'"' -f2)
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_OUTPUT
          echo "Server version: $SERVER_VERSION"

      - name: Build and push operator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./crates/openapi-k8s-operator/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_OPERATOR }}:${{ steps.operator-version.outputs.OPERATOR_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_OPERATOR }}:latest
          labels: |
            org.opencontainers.image.title=OpenAPI K8s Operator
            org.opencontainers.image.description=Kubernetes operator for discovering and centralizing OpenAPI documentation
            org.opencontainers.image.version=${{ steps.operator-version.outputs.OPERATOR_VERSION }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./crates/openapi-doc-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SERVER }}:${{ steps.server-version.outputs.SERVER_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_SERVER }}:latest
          labels: |
            org.opencontainers.image.title=OpenAPI Doc Server
            org.opencontainers.image.description=OpenAPI documentation server with Scalar UI
            org.opencontainers.image.version=${{ steps.server-version.outputs.SERVER_VERSION }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
