name: Release Charts

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
          
          # Check if it's a pre-release
          if [[ "$VERSION" == *"-"* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
            echo "This is a pre-release version"
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
            echo "This is a final release version"
          fi

      - name: Update Chart.yaml with release version
        run: |
          # Update Chart.yaml with the Git tag version
          sed -i "s/^version: .*/version: ${{ steps.version.outputs.VERSION }}/" helm/openapi-k8s-operator/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"${{ steps.version.outputs.VERSION }}\"/" helm/openapi-k8s-operator/Chart.yaml
          
          echo "Updated Chart.yaml:"
          echo "  version: ${{ steps.version.outputs.VERSION }}"
          echo "  appVersion: ${{ steps.version.outputs.VERSION }}"

      - name: Update Helm values with Docker image references
        run: |
          # Update the Helm values to reference the correct Docker images
          # This will be used by the Helm chart to pull the correct Docker images
          echo "Docker images will be tagged with version: ${{ steps.version.outputs.VERSION }}"
          echo "Operator image: ghcr.io/${{ github.repository }}-operator:${{ steps.version.outputs.VERSION }}"
          echo "Server image: ghcr.io/${{ github.repository }}-server:${{ steps.version.outputs.VERSION }}"

      - name: Install Cocogitto
        run: |
          # Install Cocogitto binary
          curl -sSL https://github.com/cocogitto/cocogitto/releases/latest/download/cocogitto-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv cocogitto /usr/local/bin/
          chmod +x /usr/local/bin/cocogitto
          cocogitto --version

      - name: Generate changelog with Cocogitto
        id: changelog
        run: |
          # Generate changelog using Cocogitto
          cocogitto changelog
          
          # If no changelog was generated, create a basic one
          if [ ! -f CHANGELOG.md ]; then
            echo "# Changelog" > CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "## [${{ steps.version.outputs.VERSION }}] - $(date +%Y-%m-%d)" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
            echo "### Added" >> CHANGELOG.md
            echo "- Initial release" >> CHANGELOG.md
          fi
          
          echo "Generated changelog:"
          head -20 CHANGELOG.md

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ steps.version.outputs.IS_PRERELEASE }}
